// this file is auto generated by /tools/GenerateAst
// http://craftinginterpreters.com/representing-code.html

import * as lox from "./"

export module Expr {
  abstract class Expr {
    // ...
  }

  export class Binary extends Expr {
    constructor(public left: Expr, operator: lox.TokenType, right: Expr) {
      super();
    }
  }

  export class Group extends Expr {
    constructor(public expression: Expr) {
      super();
    }
  }

  export class Literal extends Expr {
    constructor(public value: object) {
      super();
    }
  }

  export class Unary extends Expr {
    constructor(public operator: lox.TokenType, public right: Expr) {
      super();
    }
  }
}